# Generated by Django 4.2.2 on 2023-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.CharField(choices=[('Для игр', 'Для игр'), ('Для работы', 'Для работы'), ('Для монтажа видео', 'Для монтажа видео')], default=('Для работы', 'Для работы'), max_length=17),
        ),
        migrations.AlterField(
            model_name='computer',
            name='producting_country',
            field=models.CharField(choices=[('США', 'USA'), ('Китай', 'China'), ('Корея', 'Korea'), ('Япония', 'Japan'), ('Россия', 'Russia'), ('Вьетнам', 'Vietnam'), ('Германия', 'Germany'), ('Нидерланды', 'Netherlands')], max_length=11),
        ),
    ]
